version: '3.4'

services:
  db:
    image: mongo
  shorty:
    image: registry.joelchrist.nl/shorty
    ports:
      - 8010:8080
      - 5005:5005
    links:
      - db
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/shorty-bucket.json
    volumes:
      - ./private/shorty-bucket.json:/shorty-bucket.json