version: '3.0'

services:
  db:
    image: mongo
  shorty:
    image: registry.joelchrist.nl/shorty
    ports:
      - 8010:8080
      - 5005:5005
    links:
      - db
    volumes:
      - ./private/shorty-bucket.json:/shorty-bucket.json
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /shorty-bucket.json
      VIRTUAL_HOST: shorty.joelchrist.nl,www.shorty.joelchrist.nl,shortyy.tk,www.shortyy.tk
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: shorty.joelchrist.nl,www.shorty.joelchrist.nl,shortyy.tk,www.shortyy.tk
      LETSENCRYPT_EMAIL: joel@joelchrist.nl

networks:
  default:
    external:
      name: nginx-proxy
