spring:
  data:
    mongodb:
      host: db
      database: shorty
      collection: shorties
      port: 27017
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false

shorty:
  identifier:
    length: 5

google:
  cloud:
    bucket:
      name: shorty-url-shortener
