spring:
  data:
    mongodb:
      host: db
      database: shorty
      port: 27017
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false

shorty:
  identifier:
    length: 5
